// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RJP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.AccountsModel", b =>
                {
                    b.Property<Guid>("Account_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Account_No");

                    b.Property<decimal>("Balance");

                    b.Property<DateTime>("Creation_Date");

                    b.Property<Guid>("Customer_Id");

                    b.Property<DateTime>("Modification_Date");

                    b.HasKey("Account_Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DAL.Models.CustomersModel", b =>
                {
                    b.Property<Guid>("Customer_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("Creation_Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LName")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Modification_Date");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Customer_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DAL.Models.TransactionsModel", b =>
                {
                    b.Property<Guid>("Transaction_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Account_Id");

                    b.Property<DateTime>("Creation_Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("Modification_Date");

                    b.Property<DateTime>("Transaction_Date");

                    b.Property<int>("Transaction_No");

                    b.Property<string>("Transaction_Type")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Transaction_Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
